export const FETCH_TITLES = "FETCH_TITLES";
export const FETCH_OCCUPATIONS = "FETCH_OCCUPATIONS";
export const FETCH_OCCUPATIONSTATUS = "FETCH_OCCUPATIONSTATUS";
export const FETCH_EMPLOYMENTTYPES = "FETCH_EMPLOYMENTTYPES";
export const FETCH_VEHICLEUSES = "FETCH_VEHICLEUSES";
export const FETCH_LICENSETYPES = "FETCH_LICENSETYPES";
export const FETCH_CYCLEUSES = "FETCH_CYCLEUSES";
